### ISSUE TITLE
[IDEA / FEATURE REQUEST] Make list sortable

### ISSUE THREAD

**Issue by niclasreich** [ToFran/TS3LogAnalyzer#2]
There should be a possibility to sort the list (e.g. alphabetical, most online time...)

Keep up the good work.

**Comment by tofran** [comment]
It's a SQLite database so it is sorted however o select it.
If you are talking about the [web viewer](http://tofran.com/ts/stats/), yes it would be a great addition (and I plan to do that).
But this repo **only*** contains the log analyzer, allowing you to generate the database that can be used by any other application. 
Thank you for your feedback and attention.

*for now... I may create a new repo.
