### ISSUE TITLE
Web Interface

### ISSUE THREAD

**Issue by Artapel** [ToFran/TS3LogAnalyzer#4]
Good day. Thank you for your great work.
How do i get a web interface going. Do i need to have all the files in */www.htdoc/* or how do i generate the html/php files ?

**Comment by tofran** [comment]
Hello, thank you so much.
Please read issue #2 and the newly added disclaimer b59603f
Yes I will make it public, eventually.
Regards

**Comment by Artapel** [comment]
Awesome, great to hear that you are working on it. Looking forward to it.

Thank you for your effort!

**Comment by Artapel** [comment]
Hey buddy. Do you have any news perhaps. Very Excited to get the web interface going

**Comment by Artapel** [comment]
Checking in

**Comment by Artapel** [comment]
Checking in

**Comment by Artapel** [comment]
Checking in

**Comment by Artapel** [comment]
Checking in

**Comment by Artapel** [comment]
Checking in
